Add validation
MapColonies/3d-model-ingestion-service pull request #39
Opened 2023-01-02 10:04 UTC by netanelC

Adds validations to the payload.

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✔                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Further  information:

The added validations are:

1. Validates that the model's name exists in the agreed folder.
2. Validates that the tileset exists.
3. Validates the dates (startDate should be before endDate).
4. Validates the resolutionMeter (minResolutionMeter should be smaller maxResolutionMeter).
5. Validates the format of the footprint.
6. Validates the intersection between the footprint and the model's tileset.

2023-01-09 14:20 UTC, ronnahom96 commented on tests/integration/model/controllers/modelsController.spec.ts
> +      // it('productSource should be equal to modelPath', async function () {
delete comments

2023-01-09 14:20 UTC, ronnahom96 commented on tests/unit/job/models/jobsManager.spec.ts
> +      mockAxios.post.mockRejectedValue(Error('Job service is not available'));
Don't use Error with new.
https://www.geeksforgeeks.org/difference-between-throw-errormsg-and-throw-new-errormsg/

2023-01-09 14:20 UTC, ronnahom96 commented on tests/unit/model/models/modelsManager.spec.ts
> +      flowsManagerMock.createFlow.mockRejectedValue(Error('Flow service is not available'));
Use new Error instead of Error
https://www.geeksforgeeks.org/difference-between-throw-errormsg-and-throw-new-errormsg/

2023-01-09 14:20 UTC, ronnahom96 commented on tests/unit/src/common/utils/calculatePolygonFromTileset.spec.ts
> +            [35.344873270618564, 32.607986972892675],
move it to another file

2023-01-09 14:21 UTC, ronnahom96 requested changes
congratulations Nati

2023-01-09 14:25 UTC, netanelC commented on package.json
> +    "fs": "^0.0.1-security",
This is the latest version of 'fs'

2023-01-09 14:49 UTC, netanelC commented on src/common/models/errors.ts
> +export interface HttpError extends Error {
Done

2023-01-09 14:49 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +  // The center coords of the sphere in WGS84 (x, y)
Done

2023-01-09 14:49 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +  // const projection: string = config.get<string>('projections.region');
Done

2023-01-09 14:50 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +  // const coord1: number[] = proj4.default(projection).forward<number[]>(shape.region);
Done

2023-01-09 14:50 UTC, netanelC commented on package.json
> +    "fs": "^0.0.1-security",
This is the latest version of 'fs'

2023-01-09 14:51 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +export const calculateSphere = (shape: BoundingSphere): Polygon => {
Done

2023-01-09 14:57 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +  const coord: number[] = [
Done

2023-01-09 14:57 UTC, netanelC commented on src/common/utils/basePathToMountPath.ts
> +//change model path from payload
Done

2023-01-09 15:26 UTC, netanelC commented on src/common/utils/basePathToMountPath.ts
> +import config from 'config';
Done

2023-01-09 15:33 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +  // Returns it as polygon shape
Done

2023-01-09 15:37 UTC, netanelC commented on src/model/models/modelsManager.ts
> +import { removeFootprintSpaces } from '../../common/utils/removeSpaces';
I created a utilities file for all the one function files

2023-01-09 15:39 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    // this.logger.debug({ msg: 'validating model path', recieved: sourcePath });
Deleted

2023-01-09 15:39 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    // this.logger.debug({ msg: 'validating tileset json file', path: payload.modelPath });
Deleted

2023-01-09 15:40 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    // this.logger.debug({ msg: 'validating model name', recieved: modelPath });
Deleted

2023-01-09 15:40 UTC, netanelC commented on src/validator/models/validationManager.ts
> +      if (shape.sphere != undefined) {
Can you explain?

2023-01-09 15:42 UTC, netanelC commented on src/validator/models/validationManager.ts
> +        throw new Error('Somehow intesection is not null and union is!');
I changed it to the AppError but it is not supposed to be a string because it is an internal service error. It doesn't suppose to occur.

2023-01-09 15:45 UTC, netanelC commented on tests/integration/model/controllers/modelsController.spec.ts
> +      // it('productSource should be equal to modelPath', async function () {
Done

2023-01-09 15:53 UTC, netanelC commented on tests/unit/job/models/jobsManager.spec.ts
> +      mockAxios.post.mockRejectedValue(Error('Job service is not available'));
I fixed back to new

2023-01-09 15:53 UTC, netanelC commented on tests/unit/model/models/modelsManager.spec.ts
> +      flowsManagerMock.createFlow.mockRejectedValue(Error('Flow service is not available'));
I fixed back to new Error

2023-01-09 15:59 UTC, netanelC commented on tests/unit/src/common/utils/calculatePolygonFromTileset.spec.ts
> +            [35.344873270618564, 32.607986972892675],
Done

2023-01-09 16:05 UTC, netanelC commented on src/common/utils/removeSpaces.ts
> +export const removeFootprintSpaces = (footprint: string): Polygon => {
Done

2023-01-10 12:01 UTC, netanelC commented on src/validator/models/validationManager.ts
> +  public validateAll(payload: Payload): boolean | string {
It is a problem because some validations are based on other validations so I can't proceed to one validation if it depended on failed validation.

2023-01-10 12:57 UTC, ronnahom96 commented on src/validator/models/validationManager.ts
> +      if (shape.sphere != undefined) {
Try to look at Open for Extension, and Closed for Modification.
If you think it is overkill to create new classes and make it generic, mark this comment as resolved.

2023-01-10 12:57 UTC, netanelC commented on src/common/utils/calculatePolygonFromTileset.ts
> +  const radian2degree: number = 180 / Math.PI;
Done

2023-01-10 12:57 UTC, netanelC commented on package.json
> +    "fs": "^0.0.1-security",
Done

2023-01-15 14:46 UTC, RonitKissis requested changes

2023-01-15 14:46 UTC, RonitKissis commented on config/default.json
>      "pvPath": "../src"
note that the pvPath is the folder inside the pod that alex needs to each, it needs to point to the path we mounted our pv (the mapping between the real folder to the folder inside the pod, ) it should be /3DModels

2023-01-15 14:46 UTC, RonitKissis commented on config/test.json
> +    "pvPath": "./tests/helpers/3Dmodels"
you have mixed up the mount path and pv path. the mount path is the path inside the Nifi machine while the pv path is for alex to reach inside the pod in order to show the options of the models for upload in the ui (and for us to check that the pv have worked)

2023-01-15 14:46 UTC, RonitKissis commented on src/common/appError.ts
> +import { StatusCodes } from 'http-status-codes';
explain in person the usage of that

2023-01-15 14:46 UTC, RonitKissis commented on src/common/models/request.ts
> +  /**
how is this connected to the validation of the folders and the footprint? if it for the future to calculate the modelId here for the Nifi instead of the JobId?

2023-01-15 14:46 UTC, RonitKissis commented on src/common/utils/utilities.ts
> +export const changeBasePathToPVPath = (modelPath: string): string => {
you *should not* change base path to pv! the pvpath is only for alex. the only conversion is from basepath to model path (for the nifi). and remember we have SourcePath attribute for the original path in the profile

2023-01-15 14:46 UTC, RonitKissis commented on src/model/controllers/modelsController.ts
> +type CreateModelHandler = RequestHandler<undefined, Flow, Payload>;
how come you are getting a flow and not a model for modelHandler?

2023-01-15 14:46 UTC, RonitKissis commented on src/validator/models/validationManager.ts
> +    payload.modelPath = changeBasePathToPVPath(payload.modelPath);
why? you need to change model path from base path to mount path

2023-01-15 14:46 UTC, RonitKissis commented on src/validator/models/validationManager.ts
> +    result = this.validateModelName(payload.modelPath);
what is the validation of the model name for exactly?

2023-01-16 08:43 UTC, netanelC commented on config/test.json
> +    "pvPath": "./tests/helpers/3Dmodels"
I didn't mixed. I needed the pv path too in order to validate the tileset json. I wrote this local test path in order to access to the test files I created

2023-01-16 09:16 UTC, netanelC commented on src/common/models/request.ts
> +  /**
Yes. And also, instead of creating a new object named "model" that contains the payload request with model id, I just added the mode id to the request and removed the "model" object.

2023-01-16 09:16 UTC, netanelC commented on src/common/utils/utilities.ts
> +export const changeBasePathToPVPath = (modelPath: string): string => {
I needed to change the base path to pv in order to validate the tileset json.

2023-01-16 09:20 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    payload.modelPath = changeBasePathToPVPath(payload.modelPath);
Explained earlier. I needed the pv path for tileset json.

2023-01-16 09:22 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    result = this.validateModelName(payload.modelPath);
Make sure that the model name is in the folder.
For example: 
If the model name is "NewYork", I want to make sure that "NewYork" is inside the pv path (the agreed folder).

2023-01-16 11:35 UTC, RonitKissis approved these changes

2023-01-29 09:12 UTC, merged