Send to store sync
MapColonies/3d-model-ingestion-service pull request #41
Opened 2023-04-20 12:34 UTC by ronnahom96

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-04-23 16:52 UTC, RonitKissis commented
note that there are conflicts that needs to be resolved
and there is only one check that was ran.

2023-04-23 16:53 UTC, RonitKissis requested changes

2023-04-23 16:53 UTC, RonitKissis commented on config/default.json
>      "mountPath": "/home/netanel/3DModels",
if the mount path and pv path are the same, because there is no real use now for mount path (was used for nifi validation- that the chosen directory is mounted) we can stick to only pv path

2023-04-23 16:53 UTC, RonitKissis commented on helm/templates/pv.yaml
why is this file removed?  it is the base YAML for creating a pv (may need it in other networks)

2023-04-23 16:53 UTC, RonitKissis commented on helm/templates/pvc.yaml
may need it in other networks?

2023-04-23 16:53 UTC, RonitKissis commented on helm/values-dev.yaml
> -  ingestionSourcePvc:
we may need this values for future deployments in other networks?

2023-04-23 16:53 UTC, RonitKissis commented on helm/values-prod.yaml
> -  ingestionSourcePvc:
we may need this values for future deployments in other networks?

2023-04-23 16:53 UTC, RonitKissis commented on helm/values-staging.yaml
> -    enabled: false
we may need this values for future deployments in other networks?

2023-04-23 16:53 UTC, RonitKissis commented on src/flow/models/flowsManager.ts
> +    this.logger.debug({ msg: 'sent to store-sync successfully' });
add the created job-id to the logger

2023-04-23 16:53 UTC, RonitKissis commented on src/model/models/modelsManager.ts
>      //TODO: use this id for ingestion- send to NiFi and use this in links. will need to change the request to catalog in post that recieves this id
did we do it with thr store-sync? that the foldername in the destination is the unique model id instead of the job id?

2023-04-23 17:00 UTC, RonitKissis commented
not all unit tests passes :(

2023-04-24 11:29 UTC, netanelC commented on helm/templates/pvc.yaml
I returned it. Needs to be checked on internal networks

2023-04-24 11:29 UTC, netanelC commented on helm/values-dev.yaml
> -  ingestionSourcePvc:
Returned

2023-04-24 11:29 UTC, netanelC commented on helm/values-prod.yaml
> -  ingestionSourcePvc:
Returned

2023-04-24 11:29 UTC, netanelC commented on helm/values-staging.yaml
> -    enabled: false
Returned

2023-04-24 11:32 UTC, netanelC commented on src/flow/models/flowsManager.ts
> +    this.logger.debug({ msg: 'sent to store-sync successfully' });
Added

2023-04-24 11:32 UTC, netanelC commented on src/model/models/modelsManager.ts
>      //TODO: use this id for ingestion- send to NiFi and use this in links. will need to change the request to catalog in post that recieves this id
Yes

2023-04-24 11:35 UTC, netanelC commented on helm/templates/pv.yaml
Returned. :)

2023-04-27 07:23 UTC, RonitKissis commented
why there are no checks running? other than license @netanelC

2023-08-22 13:42 UTC, RonitKissis commented
tests check fails

2023-08-22 14:08 UTC, RonitKissis requested changes
tests arent passing

2023-08-24 12:01 UTC, merged