footprint & tileset.json validation
MapColonies/3d-model-ingestion-service pull request #54
Opened 2023-10-22 08:30 UTC by heliprokupetz14

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore            | ✔/✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2023-10-22 09:29 UTC, netanelC requested changes
Run Prettier

2023-10-22 09:29 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    if ((first[0] == last[0] && first[1] == last[1]) && (valid)){
export the validations into two private functions

2023-10-22 09:29 UTC, netanelC commented on src/common/constants.ts
> +export const footPrintJsonSchema = {
rename this constant to footprintSchema.

2023-10-22 09:29 UTC, netanelC commented on src/validator/models/validationManager.ts
> +const ajv = new Ajv();
Should be inside the relevant function

2023-10-22 09:29 UTC, netanelC commented on src/validator/models/validationManager.ts
>    public validateTilesetJson(payload: Payload): boolean | string {
Export the 2 validations into 2 private functions instead of 2 validations in one function

2023-10-22 09:29 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> +        tilesetFilename: 'invalidtileset.json',
Create a function that returns this string instead of putting it hard coded

2023-10-22 09:29 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> +    it('returns true when the footPrint is valid and the first and last coordinate are equal', () => {
make two different tests for every validation instead of testing it all in one

2023-10-22 12:12 UTC, netanelC requested changes

2023-10-22 12:12 UTC, netanelC commented on src/validator/models/validationManager.ts
> +      return `Invalid tileset.json file!`;
Not informative enough. instead of writing "tileset.json" hard coded, write the tilesetFilename itself.
In addition, point out that this is an invalid JSON file

2023-10-22 12:12 UTC, netanelC commented on src/validator/models/validationManager.ts
> +      return 'Invalid footprint!';
Not informative enough. write also that it should be in a Polygon format. Insert also the footprint provided by the client.

2023-10-22 12:12 UTC, netanelC commented on src/validator/models/validationManager.ts
> +      return 'Wrong footprint! the first and last coordinate should be equal';
Insert also the footprint provided by the client

2023-10-22 12:12 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    const coordinate = first[0] == last[0] && first[1] == last[1];
rename the coordinate variable. It is not a coordinate, it is a boolean parameter.
You can also just return directly the result of the condition instead of putting it inside a variable

2023-10-22 12:12 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    const validatedFootPrint = ajv.compile(footprintSchema)(footprint);
Rename the validatedFootPrint parameter. Optional Name: "isPolygon"

2023-10-22 12:12 UTC, netanelC commented on tests/helpers/helpers.ts
> +export const createWrongFootprintSchema = (): unknown => {
Remove the schema from the name

2023-10-22 12:12 UTC, netanelC commented on tests/helpers/helpers.ts
> +  return 'invalidtileset.json';
Change the file name to "invalidTileset.json"

2023-10-22 12:12 UTC, netanelC commented on tests/helpers/helpers.ts
> +export function createEmptyTilesetFile() {
Where are you using this function? If you are not using it. remove it

2023-10-22 12:12 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> +    it('returns true when the file in tilesetFilename exists and a valid JSON', () => {
fix to:
```suggestion
    it('returns true when the file in tilesetFilename exists and is a valid JSON', () => {
```

2023-10-22 12:12 UTC, netanelC commented on tests/helpers/helpers.ts
> +  return 'invalidtileset.json';
```suggestion
  return 'invalidTileset.json';
```

Of course, change also the name of the file itself

2023-10-22 12:12 UTC, netanelC commented on tests/helpers/helpers.ts
> +export const createWrongFootprintSchema = (): unknown => {
```suggestion
export const createWrongFootprint = (): unknown => {
```

2023-10-22 12:12 UTC, netanelC commented on src/validator/models/validationManager.ts
> +    const validatedFootPrint = ajv.compile(footprintSchema)(footprint);
```suggestion
    const isPolygon = ajv.compile(footprintSchema)(footprint);
```

2023-10-22 12:12 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> -
Don't remove this line

2023-10-22 12:12 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> -
Don't remove this line

2023-10-22 12:12 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> -
Don't remove this line

2023-10-22 12:12 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> +    it('return "Invalid footprint!" when the footPrint is invalid', () => {
Try to be more generic in your tests

```suggestion
    it('returns error string when the footPrint is invalid', () => {
```

2023-10-23 08:42 UTC, netanelC approved these changes
Good Job!!

2023-10-23 08:43 UTC, netanelC requested changes

2023-10-23 08:43 UTC, netanelC commented on src/common/constants.ts
> +          items: { type: 'number' },
Add min and max items

2023-10-23 08:58 UTC, netanelC approved these changes
Good Job!!

2023-10-24 13:02 UTC, RonitKissis commented on src/validator/models/validationManager.ts
> +      return `Unknown tileset name! The tileset file isn't founded!, tileset: ${payload.tilesetFilename}`;
syntax error, change to: "the tileset file wasn't found" "the tileset file doesn't exist"

2023-10-24 13:04 UTC, RonitKissis commented on src/validator/models/validationManager.ts
> +      return `Invalid ${payload.tilesetFilename} file!`;
change to " tileset.json file that was provided isn't in a valid json format."

2023-10-24 13:16 UTC, RonitKissis commented on src/validator/models/validationManager.ts
> +      return `Invalid footprint of type Polygon: ${JSON.stringify(footprint)}`;
change to " invalid footprint provided. must be in a geojson form of a polygon only.Should  consist of type and coordinates only"

2023-10-24 13:17 UTC, RonitKissis commented on src/validator/models/validationManager.ts
> +      return `Wrong footprint: ${JSON.stringify(footprint)} the first and last coordinate should be equal`;
coordinates

2023-10-25 14:07 UTC, netanelC requested changes

2023-10-25 14:07 UTC, netanelC commented on src/validator/models/validationManager.ts
> +      return `Unknown tileset name! The tileset file wasn't founded!, tileset: ${payload.tilesetFilename} doesn't exist`;
```suggestion
      return `Unknown tileset name! The tileset file wasn't found!, tileset: ${payload.tilesetFilename} doesn't exist`;
```

2023-10-25 14:07 UTC, netanelC commented on src/validator/models/validationManager.ts
> +      return `Invalid footprint provided. Must be in a geogson form of a polygon only. Should of type and coordinates only: ${JSON.stringify(
```suggestion
      return `Invalid footprint provided. Must be in a GeoJson format of a Polygon. Should contain "type" and "coordinates" only: ${JSON.stringify(
```

2023-10-25 14:07 UTC, netanelC commented on tests/integration/model/controllers/modelsController.spec.ts
> +          `Unknown tileset name! The tileset file wasn't founded!, tileset: ${validRequest.tilesetFilename} doesn't exist`
```suggestion
          `Unknown tileset name! The tileset file wasn't found!, tileset: ${validRequest.tilesetFilename} doesn't exist`
```

2023-10-25 14:07 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> +    it('returns true when the footPrint is valid and the first and last coordinate are equal', () => {
```suggestion
    it('returns true when the footprint is valid and the first and last coordinate are equal', () => {
```

2023-10-25 14:07 UTC, netanelC commented on tests/unit/validator/models/validationManager.spec.ts
> +      expect(result).toBe(`Wrong footprint: ${JSON.stringify(footprint)} the first and last coordinate's should be equal`);
```suggestion
      expect(result).toBe(`Wrong footprint: ${JSON.stringify(footprint)} the first and last coordinates should be equal`);
```

2023-10-25 14:07 UTC, netanelC commented on tests/integration/model/controllers/modelsController.spec.ts
> +          `Wrong footprint: ${JSON.stringify(validRequest.metadata.footprint)} the first and last coordinate's should be equal`
```suggestion
          `Wrong footprint: ${JSON.stringify(validRequest.metadata.footprint)} the first and last coordinates should be equal`
```

2023-10-25 15:28 UTC, netanelC approved these changes

2023-10-25 15:38 UTC, merged